 <?php
/* @var $container Laminas\Navigation\Navigation */
$container = $this->container;
?>
<nav>
<ul class="navigation">
    <?php foreach ($container as $page): ?>
        <?php if (!$this->navigation()->accept($page)) continue; ?>
        <?php $hasChildren = $page->hasPages() ?>
        <?php $navDepth = $this->themeSetting('nav_depth'); ?>
        <li class="<?php if ($page->isActive()) echo 'active' ?>">
            <a href="<?php echo $page->getHref(); ?>"><?php echo $this->escapeHtml($this->translate($page->getLabel(), $this->navigation($container)->getTranslatorTextDomain())); ?></a>
            <?php 
            if ($hasChildren) {
                $access = false;
                foreach ($page->getPages() as $child) {
                    if ($this->navigation()->accept($child) && $child->get("separator") !== true) {
                        $access = true;
                    }
                }
                echo ($access) ? $this->partial('common/sub-navigation', ['container'=> $container, 'children' => $page->getPages(), 'level' => 1]) : '';
            }
            ?>
        </li>
    <?php endforeach; ?>
</ul>
</nav>