<?php
$escape = $this->plugin('escapeHtml');
$translate = $this->plugin('translate');
$this->headScript()->appendFile($this->assetUrl('js/browse.js'));
if(isset($itemSet)) {
    $this->headLink()->prependStylesheet($this->assetUrl('css/resource-page-blocks', 'Omeka'));
}
$this->htmlElement('body')->appendAttribute('class', 'item resource browse');

$query = $this->params()->fromQuery();
?>
<?php if (isset($itemSet)): ?>
<?php $this->htmlElement('body')->appendAttribute('class', 'item-set show');
    $query['item_set_id'] = $itemSet->id(); ?>
    <?php echo $this->pageTitle($itemSet->displayTitle(), 2); ?>
    <h3><?php echo $translate('Item Set'); ?></h3>
    <div class="resource-metadata">
        <?php echo $this->resourcePageBlocks($itemSet)->getBlocks(); ?>
    </div>
    <?php echo $this->pageTitle($translate('Items'), 3); ?>
<?php else: ?>
    <?php echo $this->pageTitle($translate('Items'), 2); ?>
<?php endif; ?>

<?php echo $this->searchFilters(); ?>

<?php 
    $layoutSetting = $this->themeSetting('browse_layout', 'grid');
    $gridState = ($layoutSetting == 'togglegrid') ? 'disabled' : '';
    $listState = ($layoutSetting == 'togglelist') ? 'disabled': '';
    $currentLayout = (strpos($layoutSetting, 'grid') !== false) ? 'grid' : 'list';
?>
<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php echo $this->hyperlink($translate('Advanced search'), $this->url('site/resource', ['controller' => 'item', 'action' => 'search'], ['query' => $query], true), ['class' => 'advanced-search']); ?>
    <?php echo $this->browse()->renderSortSelector('items'); ?>
    <?php if (strpos($layoutSetting, 'toggle') !== false): ?>
    <div class="layout-toggle">
        <button type="button" aria-label="<?php echo $translate('Grid'); ?>" class="grid o-icon-grid" <?php echo $gridState; ?>></button>
        <button type="button" aria-label="<?php echo $translate('List'); ?>" class="list o-icon-list" <?php echo $listState; ?>></button>        
    </div>
    <?php endif; ?>
</div>
<?php $this->trigger('view.browse.before'); ?>
<ul class="resource-list <?php echo $currentLayout; ?>">
    <?php
    $headingTerm = $this->siteSetting('browse_heading_property_term');
    $bodyTerm = $this->siteSetting('browse_body_property_term');
    ?>
    
    <?php foreach ($items as $item): ?>
    <?php
    $heading = $headingTerm ? $item->value($headingTerm, ['default' => $translate('[Untitled]')]) : $item->displayTitle();
    $body = $bodyTerm ? $item->value($bodyTerm) : $item->value('dcterms:date');
    ?>
    <li class="item resource">
        <?php if ($thumbnail = $this->thumbnail($item, 'medium')): ?>
        <?php echo $item->linkRaw($thumbnail, null, ['class' => 'thumbnail']); ?>
        <?php endif; ?>
        <div class="resource-meta">
            <h4><?php echo $item->linkRaw($heading); ?></h4>
            <div class="date"><?php echo $escape($body); ?></div>
        </div>
    </li>
    <?php endforeach; ?>
</ul>
<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>
<?php $this->trigger('view.browse.after'); ?>
