<?php
$escape = $this->plugin('escapeHtml');
$translate = $this->plugin('translate');
$thumbnail = $this->plugin('thumbnail');
$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;

$this->headScript()->appendFile($this->assetUrl('js/browse.js'));
if(isset($itemSet)) {
    $this->headLink()->prependStylesheet($this->assetUrl('css/resource-page-blocks', 'Omeka'));
}
$this->htmlElement('body')->appendAttribute('class', 'item resource browse');

$query = $this->params()->fromQuery();
?>
<?php if (isset($itemSet)): ?>
<?php $this->htmlElement('body')->appendAttribute('class', 'item-set show');
    $query['item_set_id'] = $itemSet->id(); ?>
    <?php echo $this->pageTitle($itemSet->displayTitle(null, $valueLang), 2); ?>
    <h3><?php echo $translate('Item Set'); ?></h3>
    <div class="resource-metadata">
        <?php echo $this->resourcePageBlocks($itemSet)->getBlocks(); ?>
    </div>
    <?php echo $this->pageTitle($translate('Items'), 3); ?>
<?php else: ?>
    <?php echo $this->pageTitle($translate('Items'), 2); ?>
<?php endif; ?>

<?php echo $this->searchFilters(); ?>

<?php 
    $layoutSetting = $this->themeSetting('browse_layout', 'grid');
    $gridState = ($layoutSetting == 'togglegrid') ? 'disabled' : '';
    $listState = ($layoutSetting == 'togglelist') ? 'disabled': '';
    $currentLayout = (strpos($layoutSetting, 'grid') !== false) ? 'grid' : 'list';
?>
<div class="browse-controls">
    <?php if (strpos($layoutSetting, 'toggle') !== false): ?>
    <div class="layout-toggle">
        <button type="button" aria-label="<?php echo $translate('Grid'); ?>" class="grid o-icon-grid" <?php echo $gridState; ?>></button>
        <button type="button" aria-label="<?php echo $translate('List'); ?>" class="list o-icon-list" <?php echo $listState; ?>></button>        
    </div>
    <?php endif; ?>
    <?php echo $this->hyperlink($translate('Advanced search'), $this->url('site/resource', ['controller' => 'item', 'action' => 'search'], ['query' => $query], true), ['class' => 'advanced-search']); ?>
    <?php echo $this->pagination(); ?>
    <?php echo $this->browse()->renderSortSelector('items'); ?>
</div>
<?php $this->trigger('view.browse.before'); ?>
<ul class="resource-list <?php echo $currentLayout; ?>">
    <?php
    $headingTerm = $this->siteSetting('browse_heading_property_term');
    $bodyTerm = $this->siteSetting('browse_body_property_term');
    ?>    
    <?php foreach ($items as $item): ?>
    <li class="item resource">
        <?php
        $heading = $headingTerm ? $item->value($headingTerm, ['default' => $translate('[Untitled]'), 'lang' => $valueLang]) : $item->displayTitle(null, $valueLang);
        $body = $bodyTerm ? $item->value($bodyTerm, ['lang' => $valueLang]) : $item->displayDescription(null, $valueLang);
        $linkContent = sprintf('%s<span class="resource-name">%s</span>',
            $thumbnail($item, 'medium'),
            $escape($heading));
        echo $item->linkRaw($linkContent, null, ['class' => 'resource-link']);
        ?>
        <?php if ($body): ?>
        <div class="description"><?php echo $escape($body); ?></div>
        <?php endif; ?>
    </li>
    <?php endforeach; ?>
</ul>
<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>
<?php $this->trigger('view.browse.after'); ?>
