<?php 
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$this->headScript()->prependFile($this->assetUrl('js/jquery.chocolat.min.js'));
$this->headLink()->prependStylesheet($this->assetUrl('css/chocolat.css'));
$subjects = $item->subjectValues();
$sortedSubjects = [];
$subjects = $item->subjectValues();
foreach ($subjects as $value) {
    $resource = $value->resource();
    $property = $value->property();
    $sortedSubjects[$property->label()][] = $resource;
}
?>

<script>
    jQuery(document).ready(function(){
        var inContainer = jQuery("#itemfiles-nav").Chocolat({
        imageSize: "default",
        loop: true,
        fullscreen: true,
        container: "#itemfiles"
        }).data("chocolat");

        if (typeof inContainer != "undefined") {
            inContainer.api().open()
        }
    });
</script>

<?php echo $this->pageTitle($item->displayTitle(), 2); ?>
<h3><?php echo $this->translate('Item'); ?></h3>
<?php if ($item->media()): ?>
<div id="itemfiles" style="width: 100%; height: 50vh; background: #E0E0E0; margin:auto;"></div>
<div id="itemfiles-nav" class="media-list">
    <?php foreach ($item->media() as $media): ?>
        <a href="<?php echo $media->originalUrl(); ?>" class="media resource chocolat-image">
            <img src="<?php echo $escape($media->thumbnailUrl('medium')); ?>" title="<?php echo $escape($media->displayTitle()); ?>">
        </a>
    <?php endforeach; ?>
</div>
<?php endif; ?>
<?php echo $item->displayValues(); ?>

<?php $itemSets = $item->itemSets(); ?>
<?php if (count($itemSets) > 0): ?>
<div class="property">
    <h4><?php echo $this->translate('Item Sets'); ?></h4>
    <?php foreach ($item->itemSets() as $itemSet): ?>
    <div class="value"><a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(); ?></a></div>
    <?php endforeach; ?>
</div>
<?php endif; ?>

<?php if ($subjects): ?>
<div id="item-linked">
    <h3><?php echo $this->translate('Linked resources'); ?></h3>
    <div class="property">
    <?php foreach ($sortedSubjects as $property => $resources): ?>
        <h4><?php echo $this->translate(sprintf('As "%s"', $property)); ?></h4>
        <?php foreach ($resources as $resource): ?>
        <div class="resource value">
                <?php if ($thumbnail = $resource->primaryMedia()): ?>
                <a href="<?php echo $resource->url(); ?>"><img
                    src="<?php echo $escape($thumbnail->thumbnailUrl('square')); ?>"
                    title="<?php echo $escape($thumbnail->displayTitle()); ?>"
                    alt="<?php echo $escape($thumbnail->mediaType()); ?> thumbnail"
                ></a>
            <?php endif; ?>
            <?php echo $resource->link($resource->displayTitle()); ?>
        </div>
        <?php endforeach; ?>
    <?php endforeach; ?>
    </div>
</div>
<?php endif; ?>

<?php $this->trigger('view.show.after'); ?>
