<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');

$embedMediaSetting = $this->siteSetting('item_media_embed');
$itemMedia = $item->media();
if ($embedMediaSetting == 1) {
    $sortedMedia = $this->SortMedia($itemMedia);
    $lightMedia = (isset($sortedMedia['lightMedia'])) ? $sortedMedia['lightMedia'] : null;
    $otherMedia = (isset($sortedMedia['otherMedia'])) ? $sortedMedia['otherMedia'] : null;
} else {
    $otherMedia = $itemMedia;
}
?>

<?php echo $this->pageTitle($item->displayTitle(), 2); ?>
<h3><?php echo $this->translate('Item'); ?></h3>

<div class="resource-metadata">
    <?php echo $this->resourcePageBlocks($item); ?>
    <?php $this->trigger('view.show.after'); ?>
</div>

</div>
