<?php 
$this->htmlElement('body')->appendAttribute('class', 'media resource show'); 
$mediaCaption = $this->themeSetting('media_caption');
$mediaType = $media->mediaType();
$enableLightGallery = strpos($mediaType, 'image') !== false;
?>

<?php echo $this->pageTitle($media->displayTitle(), 2); ?>
<h3><?php echo $this->translate('Media'); ?></h3>
<div class="resource-metadata">
    <?php $this->trigger('view.show.before'); ?>
    <?php echo $this->resourcePageBlocks($media); ?>
    <?php $this->trigger('view.show.after'); ?>
</div>