<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->headLink()->appendStylesheet($this->assetUrl('css/lightslider.min.css'));
$this->headLink()->appendStylesheet($this->assetUrl('css/lightgallery.min.css'));
$this->headScript()->appendFile($this->assetUrl('js/lightslider.min.js'));
$this->headScript()->appendFile($this->assetUrl('js/lightgallery.min.js'));
$this->headScript()->appendFile($this->assetUrl('js/lg-video.min.js'));
$this->headScript()->appendFile($this->assetUrl('js/lg-zoom.js'));

?>
<div class="item-with-metadata">
<?php foreach($attachments as $attachment): ?>
    <?php 
      $item = $attachment->item(); 
      $imageMedia = [];
      $otherMedia = [];
      foreach ($item->media() as $media) {
          $mediaType = $media->mediaType();
          $mediaRenderer = $media->renderer();
          if ((strpos($mediaType, 'image/') !== false) || (strpos($mediaRenderer, 'youtube') !== false)) {
              $imageMedia[] = $media;
          } else {
              $otherMedia[] = $media;
          }
      }
    ?>
    <?php if (empty($item)) continue; ?>

    <div class="resource show">
        <?php if (count($imageMedia) > 0): ?>
        <ul class="lightgallery media-list">
            <?php foreach ($imageMedia as $media): ?>
                <?php $source = ($media->originalUrl()) ? $media->originalUrl() : $media->source(); ?>
                <li data-src="<?php echo $source; ?>" data-thumb="<?php echo $escape($media->thumbnailUrl('medium')); ?>"  data-download-url="<?php echo $source; ?>" class="media resource">
                    <?php echo $media->render(); ?>
                </li>
            <?php endforeach; ?>
        </ul>
        <?php endif; ?>

        <?php echo $item->displayValues(); ?>

        <?php if($item->itemSets()): ?>
            <div class="property">
                <h4><?php echo $translate('Item sets'); ?></h4>
                <div class="values">
                    <?php foreach ($item->itemSets() as $itemSet): ?>
                    <div class="value"><?php echo $itemSet->link($itemSet->displayTitle()); ?></div>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endif; ?>

        <?php if (count($otherMedia) > 0): ?>
        <div id="other-media" class="property">
            <h4><?php echo $this->translate('Other Media'); ?></h4>
            <div class="values">
                <?php foreach($otherMedia as $media): ?>
                <div class="value">
                    <a href="<?php echo $media->siteUrl(); ?>"><?php echo $media->displayTitle(); ?></a>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
        <?php endif; ?>

    </div>
<?php endforeach; ?>
</div>
