<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Crimson+Text:400,400italic,700,700italic');
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->appendStylesheet($this->assetUrl('css/style.css'));
$this->headScript()->prependFile($this->assetUrl('js/centerrow.js'));
$this->headScript()->prependFile($this->assetUrl('js/jquery-accessibleMegaMenu.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->jsTranslate();
$banner = $this->themeSettingAssetUrl('banner');
$bannerHeight = $this->themeSetting('banner_height');
$bannerHeightMobile = $this->themeSetting('banner_height_mobile');
$bannerPosition = ($this->themeSetting('banner_position')) ? str_replace('_','-', $this->themeSetting('banner_position')) : 'center';
$this->trigger('view.layout');
$userBar = $this->userBar();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
        <style>
            .banner {
                height: <?php echo ($bannerHeight !== '') ? $bannerHeight: 'auto'  ?>;
                align-items: <?php echo $bannerPosition; ?>;
            }
        <?php if ($bannerHeightMobile !== ''): ?>
            @media screen and (max-width:640px) {
                .banner {
                    height: <?php echo $bannerHeightMobile; ?>;
                }
            }
        <?php endif; ?>
        </style>
    </head>

    <?php echo $this->htmlElement('body'); ?>
        <a id="skipnav" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>
        <?php echo $userBar; ?>
        <div id="wrap">
            <header>
                <h1>
                    <a href="<?php echo $site->url(); ?>" class="site-title">
                    <?php if ($this->themeSetting('logo')): ?>
                        <img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
                    <?php else: ?>
                        <?php echo $escape($siteTitle); ?>
                    <?php endif; ?>
                    </a>
                </h1>
                <div id="search-container">
                    <?php echo $this->partial('common/search-form'); ?>
                    <button type="button" class="search-toggle" title="Toggle search"></button>
                </div>
                <?php echo $site->publicNav()->menu()->setPartial('common/accessible-mega-menu.phtml')->renderPartial(); ?>

                <?php if ($banner): ?>
                <div class="banner">
                    <img src="<?php echo $this->themeSettingAssetUrl('banner'); ?>" title="Banner">
                </div>
                <?php endif; ?>
            </header>

            <div id="content" role="main">
                <?php echo $this->content; ?>
            </div>

            <footer>
                <?php if ($footerContent = $this->themeSetting('footer')): ?>
                <?php echo $footerContent; ?>
                <?php else: ?>
                    <?php echo $this->translate('Powered by Omeka S'); ?>
                <?php endif; ?>
            </footer>
        </div>
        <script type="text/javascript">
        jQuery(document).ready(function () {
            CenterRow.mobileMenu();
            CenterRow.megaMenu();
        });
        </script>
    </body>
</html>
